// Basic expressions, statements and formatting
int a = 7, b = 3;
Console.WriteLine(a + b);
Console.WriteLine(a - b * 2);
Console.WriteLine(a / b);
Console.WriteLine(a % b);
Console.WriteLine(-a / 2);
Console.WriteLine(7.0 / 2);
Console.WriteLine(1.0 / 3);
Console.WriteLine(a << 2 | 1);
Console.WriteLine(~a & 0xFF);
Console.WriteLine(-16 >> 2);
Console.WriteLine(-16 >>> 28);
Console.WriteLine(a > b && b > 0);
Console.WriteLine(a == 7 ? "seven" : "other");
double d = 2.5;
Console.WriteLine(d * 2);
Console.WriteLine(10 / 4.0);
Console.WriteLine(0.1 + 0.2);
Console.WriteLine(1e20);
Console.WriteLine(123456789.125);
Console.WriteLine((int)3.99);
Console.WriteLine((int)-3.99);
Console.WriteLine((char)65);
Console.WriteLine('a' + 1);
Console.WriteLine((char)('a' + 1));
char c = 'x';
c++;
Console.WriteLine(c);
byte by = 250;
by += 10;
Console.WriteLine(by);
string s = "abc";
s += 'd';
s += 5;
Console.WriteLine(s);
Console.WriteLine($"a={a}, b={b,4}, d={d:F2}, hex={255:X4}, pad=[{"x",-3}]");
Console.WriteLine(string.Format("{0} + {1} = {2}", 1, 2, 1 + 2));
Console.WriteLine("{0:N2}", 1234567.891);
Console.WriteLine($"{0.256:P1}");
Console.WriteLine(true);
Console.WriteLine(null == null);
int? n = null;
Console.WriteLine(n ?? 42);
n ??= 5;
Console.WriteLine(n);
var total = 0;
for (int i = 0; i < 10; i++) { if (i == 7) break; if (i % 2 == 0) continue; total += i; }
Console.WriteLine(total);
int k = 0;
while (k < 5) k++;
do { k--; } while (k > 2);
Console.WriteLine(k);
int day = 3;
switch (day) {
    case 1: Console.WriteLine("Mon"); break;
    case 2: case 3: Console.WriteLine("Tue/Wed"); break;
    default: Console.WriteLine("Other"); break;
}
string word = "beta";
switch (word) { case "alpha": Console.WriteLine(1); break; case "beta": Console.WriteLine(2); break; }
var size = day switch { 1 => "small", < 5 => "medium", _ => "large" };
Console.WriteLine(size);
checked { Console.WriteLine(int.MaxValue); }
Console.WriteLine(int.MaxValue + 1);
Console.WriteLine(Math.Max(3, 9) + Math.Abs(-2));
Console.WriteLine(Math.Sqrt(16));
Console.WriteLine(Math.Round(2.5) + " " + Math.Round(3.5) + " " + Math.Round(2.345, 2));
Console.WriteLine(Math.Floor(-1.5));
const int LIMIT = 10 * 2;
Console.WriteLine(LIMIT);
Console.WriteLine(10.ToString("D4"));
Console.WriteLine(3.14159.ToString("F2"));
Console.WriteLine(int.Parse("  -123 ") + 1);
Console.WriteLine(double.Parse("1.5") * 2);
Console.WriteLine(Convert.ToInt32("42") + Convert.ToInt32(2.5) + Convert.ToInt32(3.5));
Console.WriteLine(Convert.ToString(255, 2));
Console.WriteLine(Convert.ToString(255, 16));
Console.WriteLine(1_000_000);
Console.WriteLine(0b1010);
Console.WriteLine(double.NaN);
Console.WriteLine(1.0 / 0);
Console.WriteLine(@"C:\path\file");
Console.WriteLine("tab\tnew\\line");
