# YAFFS2 on storage_partition instead of Zephyr's LittleFS:
#   west build -b <board> ports/zephyr/example -- -DEXTRA_CONF_FILE=overlay-yaffs2.conf
# (yaffs2 is downloaded at build time; GPLv2 or commercial licence)
CONFIG_MICROCS_YAFFS2=y
CONFIG_FILE_SYSTEM=n
CONFIG_FILE_SYSTEM_LITTLEFS=n
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
