// MicroPython configuration for the MicroCS comparison (bench/compare/README.md):
// a typical MCU feature level, speed options on, no filesystem/network modules.
#include <port/mpconfigport_common.h>
// Feature level of a typical MCU port (stm32/rp2 use EXTRA_FEATURES)
#define MICROPY_CONFIG_ROM_LEVEL                (MICROPY_CONFIG_ROM_LEVEL_EXTRA_FEATURES)
#define MICROPY_ENABLE_COMPILER                 (1)
#define MICROPY_PERSISTENT_CODE_LOAD            (1)
#define MICROPY_ENABLE_GC                       (1)
#define MICROPY_PY_GC                           (1)
#define MICROPY_FLOAT_IMPL                      (MICROPY_FLOAT_IMPL_DOUBLE)
#define MICROPY_LONGINT_IMPL                    (MICROPY_LONGINT_IMPL_MPZ)
#define MICROPY_OPT_COMPUTED_GOTO               (1)
#define MICROPY_OPT_MAP_LOOKUP_CACHE            (1)
#define MICROPY_OPT_LOAD_ATTR_FAST_PATH         (1)
#define MICROPY_ENABLE_SOURCE_LINE              (1)
#define MICROPY_ERROR_REPORTING                 (MICROPY_ERROR_REPORTING_TERSE)
#define MICROPY_PY_SYS_STDFILES                 (0)
#define MICROPY_PY_IO                           (0)
#define MICROPY_PY_OS                           (0)
#define MICROPY_PY_TIME                         (0)
#define MICROPY_PY_SELECT                       (0)
#define MICROPY_PY_RANDOM                       (0)
#define MICROPY_PY_JSON                         (0)
#define MICROPY_PY_RE                           (0)
#define MICROPY_PY_HEAPQ                        (0)
#define MICROPY_PY_HASHLIB                      (0)
#define MICROPY_PY_BINASCII                     (0)
#define MICROPY_PY_DEFLATE                      (0)
#define MICROPY_PY_PLATFORM                     (0)
#define MICROPY_PY_ASYNCIO                      (0)
#define MICROPY_PY_FRAMEBUF                     (0)
#define MICROPY_PY_MACHINE                      (0)
#define MICROPY_VFS                             (0)
#define MICROPY_PY_BUILTINS_INPUT               (0)
#define MICROPY_PY_SYS_PLATFORM                 "cortex-m"
#define MICROPY_HW_BOARD_NAME                   "emu"
#define MICROPY_HW_MCU_NAME                     "cortex-m"
#define MP_SSIZE_MAX (0x7fffffff)
#define MICROPY_PY_UCTYPES (0)
