#!/usr/bin/env python3
"""Write a project config header (mcs_user_config.h) with a profile's defaults.

config/mcs_user_config.h holds every option with the defaults of the full
profile. This tool writes the same file with the defaults of another profile:

    python3 tools/gen_config.py --profile lowram -o mcs_user_config.h
    python3 tools/gen_config.py --profile auto --ram-kb 20 --flash-kb 128 -o mcs_user_config.h
    python3 tools/gen_config.py --profile min -D MCS_ENABLE_TINYFS=1 -o mcs_user_config.h

Profiles: full, auto, embedded, mcu, lowram, tiny, min, linux.
-D NAME=VALUE sets an option (written into the header, not just added).
--check verifies that the template matches include/mcs_config.h (make check).
Needs a C compiler (cc, gcc or clang; $CC wins) for the preprocessor.
"""
import argparse, os, re, shutil, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE = os.path.join(ROOT, "config", "mcs_user_config.h")
NOT_OPTIONS = {"MCS_FLASHFS_FORMAT_IF_NEEDED"}  # guards of constants, not options
PROFILES = ["full", "auto", "embedded", "mcu", "lowram", "tiny", "min", "linux"]
OPT = re.compile(r"^#ifndef (MCS_\w+)\n#define (\1)(\s+)(.*?)(\s*/\*.*\*/)?\n#endif\n", re.M)


def cc():
    c = os.environ.get("CC")
    if c:
        return c.split()
    for c in ("cc", "gcc", "clang"):
        if shutil.which(c):
            return [c]
    raise SystemExit("gen_config: no C compiler found (set CC)")


def preprocess(text, defs, dump=False):
    """Run the preprocessor on text with include/ on the path."""
    with tempfile.TemporaryDirectory() as d:
        f = os.path.join(d, "t.c")
        with open(f, "w") as o:
            o.write(text)
        cmd = cc() + ["-E", "-P", "-I", os.path.join(ROOT, "include"), "-DMCS_USER_CONFIG=0"]
        cmd += (["-dM"] if dump else []) + ["-D" + x for x in defs] + [f]
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode:
            raise SystemExit("gen_config: preprocessor failed:\n" + r.stderr)
        return r.stdout


def profile_values(defs):
    """Macros include/mcs_config.h ends up with for these -D flags."""
    out = preprocess('#include "mcs_config.h"\n', defs, dump=True)
    vals = {}
    for line in out.splitlines():
        m = re.match(r"#define (MCS_\w+) ?(.*)", line)
        if m:
            vals[m.group(1)] = m.group(2).strip()
    return vals


def options(text):
    return [(m.group(1), m.group(4).strip()) for m in OPT.finditer(text)]


def differing(text, defs):
    """Options whose template value differs from the profile's value."""
    vals = profile_values(defs)
    probe = ['#include "mcs_config.h"']
    strings = []
    for n, v in options(text):
        if n not in vals or n == "MCS_PROFILE":
            continue
        if v.startswith('"') or vals[n].startswith('"') or re.match(r"U8(G2|X8)_", v):   # strings, X-macro lists
            if " ".join(v.split()) != " ".join(vals[n].split()):
                strings.append(n)
            continue
        probe += [f"#if ({n}) != ({v})", f'@DIFF "{n}"', "#endif"]
    out = preprocess("\n".join(probe) + "\n", defs)
    diff = re.findall(r"@DIFF \"(\w+)\"", out) + strings
    return {n: vals[n] for n in diff}, vals


def generate(profile, ram, flash, extra):
    text = open(TEMPLATE).read()
    pname = "MCS_PROFILE_" + profile.upper()
    defs = ["MCS_PROFILE=" + pname] + extra
    if profile == "auto":
        if not (ram and flash):
            raise SystemExit("gen_config: --profile auto needs --ram-kb and --flash-kb")
        defs += [f"MCS_TARGET_RAM_KB={ram}", f"MCS_TARGET_FLASH_KB={flash}"]
    elif ram or flash:
        raise SystemExit("gen_config: --ram-kb / --flash-kb are for --profile auto")
    diff, _ = differing(text, defs)
    for d in extra:                       # -D NAME=VALUE: written as given
        n, _, v = d.partition("=")
        diff[n] = v or "1"

    def sub(m):
        n = m.group(1)
        if n not in diff:
            return m.group(0)
        return f"#ifndef {n}\n#define {n}{m.group(3)}{diff.pop(n)}{m.group(5) or ''}\n#endif\n"
    text = OPT.sub(sub, text)
    for n in [n for n in diff if n in ("MCS_TARGET_RAM_KB", "MCS_TARGET_FLASH_KB", "MCS_PORT_HAL")
              or re.search(r"^//#define %s\b" % n, text, re.M)]:
        text, k = re.subn(r"^//#define %s\b *\S+" % n, f"#define {n} {diff[n]}", text, count=1, flags=re.M)
        if k:
            diff.pop(n)
    if profile == "auto":
        for n, v in (("MCS_TARGET_RAM_KB", ram), ("MCS_TARGET_FLASH_KB", flash)):
            text = re.sub(r"^//#define %s\b *\S+" % n, f"#ifndef {n}\n#define {n} {v}\n#endif", text, count=1, flags=re.M)
    if diff:
        raise SystemExit("gen_config: unknown option(s) " + ", ".join(sorted(diff)))
    text = re.sub(r"^#define MCS_USER_CONFIG_PROFILE(\s+)\w+", r"#define MCS_USER_CONFIG_PROFILE\g<1>" + pname, text, flags=re.M)
    head = f"/* Generated by: tools/gen_config.py --profile {profile}"
    head += (f" --ram-kb {ram} --flash-kb {flash}" if profile == "auto" else "")
    head += "".join(f" -D {d}" for d in extra) + " */\n"
    return head + text


def check():
    text = open(TEMPLATE).read()
    ok = True
    names = [n for n, _ in options(text)]
    dup = sorted({n for n in names if names.count(n) > 1})
    if dup:
        print("gen_config --check: listed twice:", ", ".join(dup)); ok = False
    diff, _ = differing(text, ["MCS_PROFILE=MCS_PROFILE_FULL"])
    for n, v in sorted(diff.items()):
        print(f"gen_config --check: template {n} differs from the default {v}"); ok = False
    listed = set(names) | set(re.findall(r"^//#define (MCS_\w+)", text, re.M))
    src = ""
    for d in ("include", "include/profiles", "modules/fs", "modules/hal", "modules/drivers", "modules/sched", "modules/shell"):
        for f in sorted(os.listdir(os.path.join(ROOT, d))) if os.path.isdir(os.path.join(ROOT, d)) else []:
            if f.endswith((".h", ".c")):
                src += open(os.path.join(ROOT, d, f), errors="replace").read()
    guards = set(re.findall(r"^#\s*ifndef (MCS_\w*H)\s*$", src, re.M))
    for n in sorted(set(re.findall(r"^#\s*ifndef (MCS_\w+)\s*$", src, re.M)) - guards - listed):
        if not n.startswith(("MCS_PROFILE", "MCS_TARGET_STM32")) and n not in NOT_OPTIONS:
            print(f"gen_config --check: option {n} is missing from config/mcs_user_config.h"); ok = False
    for p in PROFILES:                    # every profile must generate and compile
        a = ["--ram-kb", "32", "--flash-kb", "256"] if p == "auto" else []
        hdr = generate(p, 32 if a else 0, 256 if a else 0, [])
        with tempfile.TemporaryDirectory() as d:
            open(os.path.join(d, "mcs_user_config.h"), "w").write(hdr)
            gen, _ = differing(hdr.split("\n", 1)[1], ["MCS_PROFILE=MCS_PROFILE_" + p.upper()] +
                               (["MCS_TARGET_RAM_KB=32", "MCS_TARGET_FLASH_KB=256"] if a else []))
            if gen:
                print(f"gen_config --check: profile {p}: generated values differ: {sorted(gen)}"); ok = False
    print("gen_config --check: " + ("OK" if ok else "FAILED"))
    return ok


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--profile", default="full", choices=PROFILES)
    ap.add_argument("--ram-kb", type=int, default=0, help="target RAM (auto profile)")
    ap.add_argument("--flash-kb", type=int, default=0, help="target flash (auto profile)")
    ap.add_argument("-D", dest="defines", action="append", default=[], metavar="NAME=VALUE")
    ap.add_argument("-o", dest="out", help="output file (default: stdout)")
    ap.add_argument("--check", action="store_true", help="verify the template (make check)")
    a = ap.parse_args()
    if a.check:
        sys.exit(0 if check() else 1)
    for d in a.defines:
        if not re.match(r"^MCS_\w+(=.*)?$", d):
            raise SystemExit(f"gen_config: bad -D {d}")
    text = generate(a.profile, a.ram_kb, a.flash_kb, a.defines)
    if a.out:
        with open(a.out, "w") as f:
            f.write(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
