#!/usr/bin/env python3
"""Generate build/cm/bench_scripts.h for ports/cortex-m/bench.c: every
bench/mcu/*.cs as source text, optimized image and unoptimized (-O0) image."""
import glob, json, os, subprocess, sys, tempfile
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
mcs = os.path.join(root, "mcs")
out = sys.argv[1]
names, rows = [], []
def image(path, extra):
    with tempfile.NamedTemporaryFile(suffix=".mcsb", delete=False) as t: tmp = t.name
    subprocess.check_call([mcs, "-c", path, "-o", tmp] + extra, stderr=subprocess.DEVNULL)
    data = open(tmp, "rb").read(); os.unlink(tmp); return data
def arr(name, data):
    body = ",".join(str(b) for b in data)
    return "static const unsigned char %s[] __attribute__((aligned(4))) = {%s};\n" % (name, body)
with open(out, "w") as f:
    f.write("/* generated by tools/gen_bench_h.py */\n")
    only = os.environ.get("BENCH_ONLY", "").split(",") if os.environ.get("BENCH_ONLY") else None
    for p in sorted(glob.glob(os.path.join(root, "bench", "mcu", "*.cs"))):
        n = os.path.splitext(os.path.basename(p))[0]
        if only and n not in only: continue
        src = open(p).read()
        f.write("static const char b_%s_src[] = %s;\n" % (n, json.dumps(src)))
        f.write(arr("b_%s_opt" % n, image(p, [])))
        f.write(arr("b_%s_o0" % n, image(p, ["-O0"])))
        names.append(n)
    f.write("typedef struct { const char* name; const char* src; const unsigned char* opt; unsigned opt_len; const unsigned char* o0; unsigned o0_len; } bench_t;\n")
    f.write("static const bench_t benches[] = {\n")
    for n in names:
        f.write('  { "%s", b_%s_src, b_%s_opt, sizeof b_%s_opt, b_%s_o0, sizeof b_%s_o0 },\n' % (n, n, n, n, n, n))
    f.write("};\n")
