# MicroCS - optional u8g2 support: the C# U8g2 / U8x8 classes (docs/U8G2.md).
#
#   MICROCS_U8G2           ON: compile the "u8g2" driver + olikraus' u8g2 library in. Default: OFF, or
#                          ON when the project's mcs_user_config.h says  #define MCS_ENABLE_U8G2 1
#   MICROCS_U8G2_DIR       the u8g2 sources: a clone of github.com/olikraus/u8g2 (csrc/), the U8g2
#                          Arduino library (src/clib/) or the csrc folder itself (also the environment
#                          variables MICROCS_U8G2_DIR / U8G2_DIR)
#   MICROCS_U8G2_DOWNLOAD  ON: download u8g2 ${MICROCS_U8G2_VERSION} once into <build>/_microcs_deps when no
#                          local copy is found (environment: MICROCS_U8G2_DOWNLOAD=1)
#   MICROCS_U8G2_DISPLAYS  displays to compile in, e.g. "ssd1306_i2c_128x64_noname;sh1106_i2c_128x64_noname"
#   MICROCS_U8G2_FONTS     U8g2 fonts in flash, e.g. "helvB10_tr;6x10_tf" (the first is the default font)
#   MICROCS_U8X8_FONTS     U8x8 fonts in flash, e.g. "chroma48medium8_r"
#                          (empty lists keep MCS_U8G2_DISPLAYS / _FONTS of mcs_user_config.h or the
#                          defaults; `python3 tools/u8g2.py displays|fonts` lists the names)
#
# Lookup order without MICROCS_U8G2_DIR: an existing `u8g2` CMake target, then u8g2/, third_party/u8g2,
# lib/u8g2, libs/u8g2, external/u8g2, components/u8g2 in the project, ../u8g2 next to MicroCS,
# MicroCS/build/third_party/u8g2-* (tools/u8g2.py fetch), an earlier download, ~/Arduino/libraries/U8g2.
# The configure step stops with instructions when none is there.
#
# Only the fonts and displays named here are linked: u8g2 is compiled with -ffunction-sections
# -fdata-sections, so the final link needs --gc-sections (pico-sdk, ESP-IDF, Zephyr, STM32CubeMX and
# the host build do this already; for your own linker command add -Wl,--gc-sections).

set(MICROCS_U8G2_VERSION "2.37.1" CACHE STRING "u8g2 release MICROCS_U8G2_DOWNLOAD fetches")
if(NOT DEFINED MICROCS_U8G2_DOWNLOAD)
    if("$ENV{MICROCS_U8G2_DOWNLOAD}" MATCHES "^(1|ON|on|YES|yes|TRUE|true)$")
        set(MICROCS_U8G2_DOWNLOAD ON)
    else()
        set(MICROCS_U8G2_DOWNLOAD OFF)
    endif()
    set(MICROCS_U8G2_DOWNLOAD ${MICROCS_U8G2_DOWNLOAD} CACHE BOOL "Download u8g2 when no local copy is found")
endif()

# out = the folder holding u8g2.h + u8x8.h inside `dir` (csrc/, src/clib/ or dir itself), "" if none
function(_microcs_u8g2_csrc out dir)
    set(_r "")
    foreach(sub csrc src/clib "")
        if(NOT _r AND EXISTS "${dir}/${sub}/u8g2.h" AND EXISTS "${dir}/${sub}/u8x8.h")
            get_filename_component(_r "${dir}/${sub}" ABSOLUTE)
        endif()
    endforeach()
    set(${out} "${_r}" PARENT_SCOPE)
endfunction()

# out = the u8g2 csrc folder (downloads it when allowed); stops with instructions when missing
function(microcs_find_u8g2 out)
    set(_user "${MICROCS_U8G2_DIR}")
    foreach(e MICROCS_U8G2_DIR U8G2_DIR)
        if(NOT _user AND DEFINED ENV{${e}})
            set(_user "$ENV{${e}}")
        endif()
    endforeach()
    if(_user)
        get_filename_component(_user "${_user}" ABSOLUTE BASE_DIR "${CMAKE_SOURCE_DIR}")
        _microcs_u8g2_csrc(_c "${_user}")
        if(NOT _c)
            message(FATAL_ERROR "MicroCS: MICROCS_U8G2_DIR=${_user} has no u8g2.h / u8x8.h (looked in csrc/, src/clib/ "
                "and the folder itself). Point it at a clone of https://github.com/olikraus/u8g2 or the U8g2 Arduino library.")
        endif()
        set(${out} "${_c}" PARENT_SCOPE)
        return()
    endif()
    set(_dl "${CMAKE_BINARY_DIR}/_microcs_deps/U8g2_Arduino-${MICROCS_U8G2_VERSION}")
    file(GLOB _fetched LIST_DIRECTORIES true "${MICROCS_DIR}/build/third_party/u8g2-*")
    list(SORT _fetched)
    list(REVERSE _fetched)
    set(_cands)
    foreach(d u8g2 third_party/u8g2 lib/u8g2 libs/u8g2 external/u8g2 components/u8g2 third_party/U8g2 lib/U8g2)
        list(APPEND _cands "${CMAKE_SOURCE_DIR}/${d}")
    endforeach()
    list(APPEND _cands "${MICROCS_DIR}/../u8g2" "${MICROCS_DIR}/third_party/u8g2" ${_fetched} "${_dl}"
         "$ENV{HOME}/Arduino/libraries/U8g2" "$ENV{HOME}/Documents/Arduino/libraries/U8g2")
    foreach(d IN LISTS _cands)
        _microcs_u8g2_csrc(_c "${d}")
        if(_c)
            set(${out} "${_c}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    if(MICROCS_U8G2_DOWNLOAD)
        set(_url "https://github.com/olikraus/U8g2_Arduino/archive/refs/tags/${MICROCS_U8G2_VERSION}.tar.gz")
        set(_tgz "${CMAKE_BINARY_DIR}/_microcs_deps/u8g2.tar.gz")
        message(STATUS "MicroCS: downloading ${_url} (MICROCS_U8G2_DOWNLOAD=ON)")
        file(DOWNLOAD "${_url}" "${_tgz}" STATUS _st TLS_VERIFY ON)
        list(GET _st 0 _code)
        if(NOT _code EQUAL 0)
            message(FATAL_ERROR "MicroCS: u8g2 download failed (${_st}); set MICROCS_U8G2_DIR to local sources")
        endif()
        execute_process(COMMAND ${CMAKE_COMMAND} -E tar xzf "${_tgz}" WORKING_DIRECTORY "${CMAKE_BINARY_DIR}/_microcs_deps"
                        RESULT_VARIABLE _rc)
        file(REMOVE "${_tgz}")
        _microcs_u8g2_csrc(_c "${_dl}")
        if(NOT _rc EQUAL 0 OR NOT _c)
            message(FATAL_ERROR "MicroCS: could not unpack ${_url}")
        endif()
        set(${out} "${_c}" PARENT_SCOPE)
        return()
    endif()
    message(FATAL_ERROR "MicroCS: u8g2 support is on (MICROCS_U8G2 / MCS_ENABLE_U8G2) but the u8g2 sources were not found.\n"
        "  Give their location:          -DMICROCS_U8G2_DIR=/path/to/u8g2   (a clone of github.com/olikraus/u8g2,\n"
        "                                 the U8g2 Arduino library or its csrc folder; environment: MICROCS_U8G2_DIR)\n"
        "  or let CMake download u8g2 ${MICROCS_U8G2_VERSION}:  -DMICROCS_U8G2_DOWNLOAD=ON\n"
        "  or fetch it once for all builds: python3 ${MICROCS_DIR}/tools/u8g2.py fetch\n"
        "  or turn it off:               -DMICROCS_U8G2=OFF / #define MCS_ENABLE_U8G2 0")
endfunction()

# name lists -> the X-macro definitions; names are checked against u8g2.h when it is known
function(_microcs_u8g2_list out macro prefix items header)
    if(NOT items)
        set(${out} "" PARENT_SCOPE)
        return()
    endif()
    if(header)
        file(READ "${header}" _h)
    endif()
    set(_v "")
    foreach(n IN LISTS items)
        string(STRIP "${n}" n)
        if(n STREQUAL "")
            continue()
        endif()
        if(prefix AND NOT n MATCHES "^${prefix}")
            set(n "${prefix}${n}")
        endif()
        if(NOT prefix)        # u8g2_Setup_x_f, x_1 and Arduino class names (U8G2_SH1106_128X64_NONAME_F_HW_I2C) work too
            if(n MATCHES "^U8G2_[A-Z0-9_]+$")
                string(TOLOWER "${n}" n)
            endif()
            string(REGEX REPLACE "^u8g2_Setup_" "" n "${n}")
            string(REGEX REPLACE "^u8g2_" "" n "${n}")
            set(_i2c OFF)
            if(n MATCHES "_(2nd_)?(hw|sw)_i2c$")
                set(_i2c ON)
            endif()
            string(REGEX REPLACE "_(2nd_)?((hw|sw)_i2c|(4w_|3w_)?(hw|sw)_spi|8080|6800)$" "" n "${n}")
            string(REGEX REPLACE "_[f12]$" "" n "${n}")
            if(_i2c AND NOT n MATCHES "_i2c_")
                string(FIND "${n}" "_" _u)                       # sh1106_128x64 -> sh1106_i2c_128x64
                string(SUBSTRING "${n}" 0 ${_u} _a)
                string(SUBSTRING "${n}" ${_u} -1 _b)
                set(n "${_a}_i2c${_b}")
            endif()
            set(_probe "u8g2_Setup_${n}_1(")
        else()
            set(_probe "${n}[]")
        endif()
        if(header)
            string(FIND "${_h}" "${_probe}" _at)
            if(_at LESS 0)
                message(FATAL_ERROR "MicroCS: u8g2 has no ${macro} '${n}' (python3 ${MICROCS_DIR}/tools/u8g2.py "
                    "${macro}s lists the names)")
            endif()
        endif()
        if(prefix STREQUAL "u8x8_font_")
            string(APPEND _v " U8X8_FONT(${n})")
        elseif(prefix)
            string(APPEND _v " U8G2_FONT(${n})")
        else()
            string(APPEND _v " U8G2_DISPLAY(${n})")
        endif()
    endforeach()
    string(STRIP "${_v}" _v)
    set(${out} "${_v}" PARENT_SCOPE)
endfunction()

# the compile definitions for MICROCS_U8G2_DISPLAYS / _FONTS / U8X8_FONTS -> MICROCS_U8G2_DEFS
function(microcs_u8g2_defs csrc)
    set(_h "")
    if(csrc)
        set(_h "${csrc}/u8g2.h")
    endif()
    set(_x "")
    if(csrc)
        set(_x "${csrc}/u8x8.h")
    endif()
    _microcs_u8g2_list(_d display "" "${MICROCS_U8G2_DISPLAYS}" "${_h}")
    _microcs_u8g2_list(_f font "u8g2_font_" "${MICROCS_U8G2_FONTS}" "${_h}")
    _microcs_u8g2_list(_xf font "u8x8_font_" "${MICROCS_U8X8_FONTS}" "${_x}")
    set(_defs MCS_ENABLE_U8G2=1)
    if(_d)
        list(APPEND _defs "MCS_U8G2_DISPLAYS=${_d}")
    endif()
    if(_f)
        list(APPEND _defs "MCS_U8G2_FONTS=${_f}")
    endif()
    if(_xf)
        list(APPEND _defs "MCS_U8X8_FONTS=${_xf}")
    endif()
    set(MICROCS_U8G2_DEFS ${_defs} PARENT_SCOPE)
endfunction()

# u8g2 for target `tgt` (the microcs library): its sources as a static library + the definitions
function(microcs_add_u8g2 tgt)
    if(TARGET u8g2 AND NOT MICROCS_U8G2_DIR)
        message(STATUS "MicroCS: u8g2 from the existing `u8g2` target")
        target_link_libraries(${tgt} PUBLIC u8g2)
        microcs_u8g2_defs("")
    else()
        microcs_find_u8g2(_csrc)
        message(STATUS "MicroCS: u8g2 from ${_csrc}")
        if(NOT TARGET microcs_u8g2)
            file(GLOB _srcs "${_csrc}/*.c")
            add_library(microcs_u8g2 STATIC ${_srcs})
            target_include_directories(microcs_u8g2 PUBLIC "${_csrc}")
            # U8G2_USE_DYNAMIC_ALLOC: every display gets its own frame buffer from the VM heap
            target_compile_definitions(microcs_u8g2 PUBLIC U8G2_USE_DYNAMIC_ALLOC)
            if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                target_compile_options(microcs_u8g2 PRIVATE -w -ffunction-sections -fdata-sections)
            endif()
        endif()
        target_link_libraries(${tgt} PUBLIC microcs_u8g2)
        microcs_u8g2_defs("${_csrc}")
    endif()
    target_compile_definitions(${tgt} PUBLIC ${MICROCS_U8G2_DEFS})
endfunction()

# MICROCS_U8G2 unset: on when the config header enables it
function(microcs_u8g2_wanted out cfg_file)
    set(_on OFF)
    if(DEFINED MICROCS_U8G2)
        set(_on ${MICROCS_U8G2})
    elseif(cfg_file AND EXISTS "${cfg_file}")
        file(STRINGS "${cfg_file}" _l REGEX "^[ \t]*#[ \t]*define[ \t]+MCS_ENABLE_U8G2[ \t]+1")
        if(_l)
            set(_on ON)
        endif()
    endif()
    set(${out} ${_on} PARENT_SCOPE)
endfunction()

# ESP-IDF / Zephyr: menuconfig (CONFIG_MICROCS_U8G2_*) fills the CMake variables that are not set;
# lists there are separated by spaces or commas
macro(microcs_u8g2_from_kconfig)
    if(NOT MICROCS_U8G2_DIR AND CONFIG_MICROCS_U8G2_DIR)
        set(MICROCS_U8G2_DIR "${CONFIG_MICROCS_U8G2_DIR}")
    endif()
    if(CONFIG_MICROCS_U8G2_DOWNLOAD)
        set(MICROCS_U8G2_DOWNLOAD ON)
    endif()
    foreach(_v U8G2_DISPLAYS U8G2_FONTS U8X8_FONTS)
        if(NOT MICROCS_${_v} AND CONFIG_MICROCS_${_v})
            string(REGEX REPLACE "[ ,]+" ";" MICROCS_${_v} "${CONFIG_MICROCS_${_v}}")
        endif()
    endforeach()
endmacro()

# ESP-IDF / Zephyr add the sources to their own component library:
# MICROCS_U8G2_SRCS, MICROCS_U8G2_INC, MICROCS_U8G2_DEFS (incl. U8G2_USE_DYNAMIC_ALLOC)
function(microcs_u8g2_sources)
    microcs_find_u8g2(_csrc)
    message(STATUS "MicroCS: u8g2 from ${_csrc}")
    file(GLOB _srcs "${_csrc}/*.c")
    set_source_files_properties(${_srcs} PROPERTIES COMPILE_OPTIONS "-w;-ffunction-sections;-fdata-sections")
    microcs_u8g2_defs("${_csrc}")
    set(MICROCS_U8G2_SRCS ${_srcs} PARENT_SCOPE)
    set(MICROCS_U8G2_INC "${_csrc}" PARENT_SCOPE)
    set(MICROCS_U8G2_DEFS ${MICROCS_U8G2_DEFS} U8G2_USE_DYNAMIC_ALLOC PARENT_SCOPE)
endfunction()
